name: Deploy MEAN Application

on:
    push:
        branches:
            -mean-ec2-docker

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "MONGO_PASSWORD=${{ secrets.MONGO_URI }}"