name: Deploy MEAN Application

on:
    push:
        branches:
            - mean-ec2-docker
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Create .env file
              run: echo "MONGO_PASSWORD=${{ secrets.MONGO_URI }}" >> .env
            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            - name: Build docker image for backend
              working-directory: server
              run: docker build -t zapbolt/gacha-tracker-backend .
            - name: Publish image to docker hub for backend
              working-directory: server
              run: docker push zapbolt/gacha-tracker-backend:latest .
            - name: Builder docker image for frontend
              working-directory: client
              run: docker push zapbolt/gacha-tracker-frontend .
            - name: Publish image to docker hub for frontend
              working-directory: server
              run: docker push zapbolt/gacha-tracker-frontend:latest .

        
    deploy:
        needs: build
        runs-on: self-hosted
        steps:
          # Step 1: Checkout repository
          - name: Checkout source
            uses: actions/checkout@v4
          - name: Pull image from docker hub
            run: docker pull zapbolt/gacha-tracker-backend:latest
          - name: Delete old container
            run: docker rm -f gacha_tracker-backend-container
          - name: Run docker container
            run: docker run -d -p 4000:4000 --name gacha_tracker-backend-container zapbolt/gacha-tracker-backend

            
